import uuid
import random
import json

# Cấu hình số lượng
NUM_CATEGORIES = 20
NUM_PRODUCTS_PER_CATEGORY = 50
NUM_VARIANTS_PER_PRODUCT = 3

# Dữ liệu mẫu để sinh tên ngẫu nhiên
ADJECTIVES = ["Premium", "Smart", "Eco", "Pro", "Ultra", "Lite", "Elegant", "Original"]
CATEGORIES_DATA = [
    "Electronics", "Computers", "Home Appliances", "Smartphones", "Photography",
    "Fashion", "Footwear", "Watches", "Accessories", "Beauty & Care",
    "Furniture", "Kitchenware", "Books", "Toys & Games", "SportsGear"
]
PRODUCT_TYPES = ["Phone", "Laptop", "Monitor", "Camera", "Headphones", "Speaker", "Shirt", "Dress", "Bed", "Table", "Backpack"]
COLORS = ["Red", "Blue", "Black", "White", "Silver", "Gold", "Green"]
SIZES = ["S", "M", "L", "XL", "XXL", "64GB", "128GB", "256GB", "8GB RAM", "16GB RAM"]

def slugify(text):
    return text.lower().replace(" ", "-").replace("&", "and")

def generate_sql():
    sql_lines = [
        "-- SEED DATA GENERATED BY PYTHON\n",
        "TRUNCATE categories, products, product_variants CASCADE;\n\n"
    ]

    # 1. Sinh Categories
    category_ids = []
    for i, name in enumerate(CATEGORIES_DATA):
        cid = str(uuid.uuid4())
        category_ids.append(cid)
        slug = slugify(name)
        sql_lines.append(f"INSERT INTO categories (id, name, slug) VALUES ('{cid}', '{name}', '{slug}');\n")
    
    sql_lines.append("\n")

    # 2. Sinh Products & Variants
    for cid in category_ids:
        for _ in range(NUM_PRODUCTS_PER_CATEGORY):
            # Tên sản phẩm ngẫu nhiên
            adj = random.choice(ADJECTIVES)
            ptype = random.choice(PRODUCT_TYPES)
            p_idx = random.randint(100, 999)
            pname = f"{adj} {ptype} {p_idx}"
            pid = str(uuid.uuid4())
            short_id = pid.split('-')[0][:6]  # Use 6 chars of UUID for uniqueness
            slug = f"{slugify(pname)}-{short_id}"
            desc = f"Description for {pname}. Optimized for search and performance test."
            
            sql_lines.append(f"INSERT INTO products (id, name, slug, description, category_id) VALUES ('{pid}', '{pname}', '{slug}', '{desc}', '{cid}');\n")

            # Sinh Variants cho Product này
            for _ in range(NUM_VARIANTS_PER_PRODUCT):
                vid = str(uuid.uuid4())
                color = random.choice(COLORS)
                size = random.choice(SIZES)
                sku = f"{ptype.upper()}-{p_idx}-{color[0]}{size[0]}-{vid[:4].upper()}"
                price = random.randint(100, 5000)
                stock = random.randint(10, 200)
                attrs = json.dumps({"color": color, "size": size})
                
                sql_lines.append(f"INSERT INTO product_variants (id, product_id, sku, price, stock_quantity, attributes) VALUES ('{vid}', '{pid}', '{sku}', {price}, {stock}, '{attrs}');\n")

    # Lưu vào file
    with open("seed_data.sql", "w", encoding="utf-8") as f:
        f.writelines(sql_lines)
    
    print(f"--- SUCCESS: Generated seed_data.sql with ~{len(sql_lines)} lines ---")

if __name__ == "__main__":
    generate_sql()
